title: Yarden Harel 
email: harel.jordan@gmail.com
description: "Hi I'm Yarden, an aspiring algorithms developer and math enthusiastic.
Here you will find brief of my professional background, and projects showcasing some of my technical skills and theoretical foundations."
theme: jekyll-theme-minimal
